[package]
name = "nes"
version = "0.1.0"
authors = ["Stian Eklund <stian.eklund@gmail.com>"]
edition = "2018"

[profile.dev]
overflow-checks = false

[dependencies]
minifb = "0.10.0"
flexi_logger = "0.14"
log = "0.4"

